// ============================================================
// ピコットゲームズ：ゲーム登録リスト
// ------------------------------------------------------------
// 新しいゲームを公開するときは、この配列の一番上に
// 下のような形で1ブロック追加するだけでOK！
//
// {
//   id: "007",                          // 3けたの通し番号
//   title: "ゲームのなまえ",
//   emoji: "🎮",                        // カードに大きく出る絵文字
//   color: "#3ff2e6",                   // カードのテーマカラー（省略可）
//   genre: "ACTION",                    // ジャンル表記（省略可）
//   age: "6歳〜",                       // 対象年齢の目安
//   author: "ニックネーム",              // 本名は書かない！
//   date: "2026-08-27",                 // 公開日
//   description: "どんなゲームか1〜2文で。",
//   controls: "そうさ方法をかんたんに",
//   path: "games/007-xxxx/index.html",  // ゲーム本体の場所
// },
// ============================================================

const GAMES = [
{
  "id": "077",
  "title": "しりとりしょうぶ",
  "genre": "WORD",
  "cat": "word",
  "emoji": "🐣",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "ひよこ・きつね・ふくろうの3だんかいのあいてと、しりとりでしょうぶ。あいてのことばのさいごの字からはじまることばを、ひらがなキーでうとう。「ん」でおわるとまけ、じかんはだんだんみじかくなる。ヒント3回、つづいたかずのベスト、あつめたことばのきろくつき。",
  "controls": "タッチ：ひらがなキーをタップして「けってい」 / キーボード：ローマ字でもじ、Enter＝けってい、Backspace＝けす",
  "path": "games/077-shiritori-duel/index.html",
  "cover": "assets/covers/077.webp"
},
{
  "id": "076",
  "title": "つなひきバトル",
  "genre": "VERSUS",
  "cat": "versus",
  "emoji": "🪢",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "れんだで つなを ひきあう 3本しょうぶ。ランプが赤の「ストップ！」で おすと すべって ピンチ、むらさきの「チャンス」は力が2ばい。2本目からは フェイントも。1台でふたり対戦、または 3段階のCPUと。れんしょうと さいそくタイムを きろく。",
  "controls": "タッチ：ふたりは 画面の上はんぶん＝P2・下はんぶん＝P1、ひとりは 画面のどこでも れんだ / キーボード：P1＝F か スペース、P2＝J か Enter",
  "path": "games/076-tug-tap/index.html",
  "cover": "assets/covers/076.webp"
},
{
  "id": "075",
  "title": "ねらってダーツ",
  "genre": "SPORTS",
  "cat": "sports",
  "emoji": "🎯",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "ゆれる ねらいマークを いい所で 止めて なげる ダーツ。301てんから ぴったり0を めざして CPU（よわい・ふつう・つよい）と しょうぶ。光る数字が 3ばいになる カウントアップも。ラウンドが すすむほど ゆれが大きくなり、平均点と ベストが 記録されるよ。",
  "controls": "タッチ：ボードを さわって ねらい、「なげる！」ボタン ／ マウス：うごかして ねらい、クリックで なげる ／ キーボード：矢印キーで ねらい、スペースキーで なげる",
  "path": "games/075-aim-darts/index.html",
  "cover": "assets/covers/075.webp"
},
{
  "id": "074",
  "title": "おさかな水そう",
  "genre": "SIM",
  "cat": "sim",
  "emoji": "🐠",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "あか・みどり・あおの えさを あげて魚を そだてる水そうゲーム。いちばん多く たべた色で おとなの すがたが かわり、ずかんは ぜんぶで20しゅるい。しんじゅを ひろって たまごや かざりを かい、カニを おいはらおう。おねがい・オートセーブ・クリアタイムの記録つき。",
  "controls": "タッチ：えさの色をえらんで水そうをタップ、しんじゅはタップかなぞってひろう / キーボード：矢印でカーソル、スペースでえさ・ひろう、1〜3で色、Q・W・E・Rでメニュー",
  "path": "games/074-fish-tank/index.html",
  "cover": "assets/covers/074.webp"
},
{
  "id": "073",
  "title": "ほしくずクラッシュ",
  "genre": "SHOOTING",
  "cat": "shooter",
  "emoji": "🚀",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "ロケットを くるくる回して すすみ、岩をうって こわすシューティング。大きい岩は われて小さくなるよ。ウェーブが すすむと 岩がはやくなり、かたい岩やUFOも出てくる。はずさず当てるコンボ、1UP、パワーアップつき。ベスト記録が のこるよ。",
  "controls": "スマホ：左のスティックで むきと前進、「うつ」ボタンでショット ／ PC：←→で回転、↑で前進、スペースでショット、Pでひとやすみ（マウスは おした方へ むいてうつ）",
  "path": "games/073-star-rocks/index.html",
  "cover": "assets/covers/073.webp"
},
{
  "id": "072",
  "title": "まねっこドラム",
  "genre": "RHYTHM",
  "cat": "rhythm",
  "emoji": "🥁",
  "color": "#ff5fa2",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "せんせいの おてほんを きいて、おなじタイミングで ドラムを たたく まねっこリズムゲーム。ぜんぶで20フレーズ、はんていは ぴったり・おしい・ミスの3だんかい。すすむほど テンポが はやくなり、ドラムも 3こに ふえるよ。ガイドなしの「みみだけ」モードと ベストきろくつき。",
  "controls": "📱 下の ドラムを タップ ／ ⌨️ F・J・K（または ← ↓ → ／ Z・X・C）で たたく",
  "path": "games/072-drum-echo/index.html",
  "cover": "assets/covers/072.webp"
},
{
  "id": "071",
  "title": "すうじのへや",
  "genre": "PUZZLE",
  "cat": "puzzle",
  "emoji": "🔢",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "たて・よこ・ふといわくの へやに、おなじ すうじが かぶらないように うめる ナンプレ。4×4・6×6・9×9の 3サイズと 3つの むずかしさで、こたえが 1つだけの もんだいを まいかい 新しく つくるよ。メモ、ミスひょうじ、ヒント、まいにち かわる「きょうの もんだい」、タイムと★の きろくつき。",
  "controls": "タッチ：マスを タップして えらび、下の すうじを タップ。✏️メモで こうほを 小さく かける / キーボード：矢印キーで いどう、すうじキーで 入力、Backspaceで けす、Mで メモ、Zで もどす、Hで ヒント / マウス：マスと すうじを クリック",
  "path": "games/071-number-place/index.html",
  "cover": "assets/covers/071.webp"
},
{
  "id": "070",
  "title": "かげあてクイズ",
  "genre": "KIDS",
  "cat": "kids",
  "emoji": "🔦",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "スクリーンにうつった かげの形を見て、なんの絵かを3つのことばからえらぶクイズ。絵は60しゅるい。こまったらヒントで少しずつ色が出るよ。まわるかげ・ズーム・ライトでさがす くらやみ など6ステージ（★3つ評価）と、どこまで続くかのチャレンジ、あてた絵があつまる ずかんつき。",
  "controls": "タッチ・マウス：ことばをタップしてこたえる、💡でヒント、くらやみではスクリーンをなぞってライトをうごかす / キーボード：1・2・3でこたえ、Hでヒント、矢印キーでライト、Enterでつぎへ、Escでやめる",
  "path": "games/070-shadow-guess/index.html",
  "cover": "assets/covers/070.webp"
},
{
  "id": "069",
  "title": "リズムつくろう",
  "genre": "CREATIVE",
  "cat": "creative",
  "emoji": "🎛️",
  "color": "#ff5fa2",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-07",
  "description": "16このマスに音をおいて、じぶんだけのリズムとメロディを作ろう。ドラム・ベース・ピコ・ベル・ふわの5つのがっきをかさねて、テンポをかえ、4つのわくにほぞんできる。お手本を耳でまねする「まねっこチャレンジ」全24ステージ（問題はまいかいかわる・★あつめ）つき。",
  "controls": "タッチ：マスをタップ／なぞって音をおく・けす、▶でならす。PC：クリック、または矢印キー＋スペースでおく、Pでならす・とめる、1〜5でがっき、＋−でテンポ",
  "path": "games/069-step-beats/index.html",
  "cover": "assets/covers/069.webp"
},
{
  "id": "060",
  "title": "ナイトビリヤード",
  "genre": "SPORTS",
  "cat": "sports",
  "emoji": "🎱",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "白い玉を ひっぱって うち、ばんごうの小さい玉から あなに おとす ビリヤード。玉が ふえて ガイド線が みじかくなる ステージせいの「ひとりで あそぶ」と、3だんかいの「CPUと たいせん」。つづけて おとすと ボーナス、ベストと かちまけの きろくつき。",
  "controls": "タッチ・マウス：台の どこでも ひっぱって はなす（うちたい むきの はんたいに ひく。長いほど 強い） / キーボード：← → で むき（Shiftで こまかく）、↑ ↓ で 強さ、スペース・Enterで うつ、Gで ガイド線",
  "path": "games/060-night-billiards/index.html",
  "cover": "assets/covers/060.webp"
},
{
  "id": "059",
  "title": "ちいさな畑",
  "genre": "SIM",
  "cat": "sim",
  "emoji": "🥕",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "たねをうえて水をやり、みのったやさいを売って畑をひろげよう。春夏秋冬でかわる8しゅるいのやさい、高ねの日、ちゅうもん、あめやカラスを読んで、20日でもくひょうのお金をめざす。畑は5つ、★とベストをきろく。とちゅうでやめても、つづきからあそべるよ。",
  "controls": "タップ／クリック：たねをえらんで畑をタップ（うえる・水やり・しゅうかく）、🌙でつぎの日へ ・ キーボード：やじるしでえらぶ、スペース／Enterでタップ、1〜4でたね、Xでスコップ、Nでねる",
  "path": "games/059-tiny-farm/index.html",
  "cover": "assets/covers/059.webp"
},
{
  "id": "067",
  "title": "ピカッとあんざん",
  "genre": "BRAIN",
  "cat": "brain",
  "emoji": "⚡",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "ピカッと光って きえる数字を あたまの中で ぜんぶ たす あんざんゲーム。けた数・こ数・はやさが かわる 20レベル。2もん せいかいで レベルアップ、ハートが なくなると おしまい。はやさボーナス、「もういちど見る」、ひきざんレベル、さいこう記録と あんざんランクつき。",
  "controls": "画面のテンキーをタップして「OK」、🔁で もういちど見る / キーボードは すうじキーで うって Enter、Backspaceで けす、Rで もういちど見る",
  "path": "games/067-flash-sum/index.html",
  "cover": "assets/covers/067.webp"
},
{
  "id": "066",
  "title": "とびこえチェッカー",
  "genre": "BOARD",
  "cat": "board",
  "emoji": "👑",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "コマをななめ前にすすめ、あいてをとびこえて取るボードゲーム。つづけてとぶ「れんぞくジャンプ」や、おくまで行くとなれる王さまが決め手。CPUは3段階（つよいは先読みつき）、ふたり対戦もOK。うごかせるコマが光り、ヒント・1手もどす、強さ別の成績と★の記録つき。",
  "controls": "コマをタップ→光った◎のマスをタップでうごかす / マウスはクリック / やじるしキー＋Enter、Z＝もどす、H＝ヒント",
  "path": "games/066-jump-checkers/index.html",
  "cover": "assets/covers/066.webp"
},
{
  "id": "065",
  "title": "スパッとフルーツ",
  "genre": "ARCADE",
  "cat": "arcade",
  "emoji": "🍉",
  "color": "#ff5fa2",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "とんでくるフルーツを ゆびでなぞって スパッ！ ひとふりで つづけて きるほど 点がふえるコンボ、ばくだんは きっちゃダメ。金のスター、スローになる こおりの実、点が2ばいのフィーバーも。60びょうと 3ミスの2モードで、レベルが上がるほど にぎやかに。ベストと★をきろく。",
  "controls": "タッチ／マウスで なぞって きる ・ キーボードは やじるし／WASDで やいばを うごかす、スペース／Enterで スタート、Pで ひとやすみ",
  "path": "games/065-fruit-slash/index.html",
  "cover": "assets/covers/065.webp"
},
{
  "id": "064",
  "title": "まっくら迷路",
  "genre": "ADVENTURE",
  "cat": "adventure",
  "emoji": "🔦",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "ランタンの ひかりが とどく ところしか 見えない めいろで、カギを あつめて とびらを めざす たんけんゲーム。めいろは まいかい かわり、3つの サイズで フロア5まで。おいかけてくる おばけは「ひかりのたま」で 止めよう。タイムと ★の きろくつき。",
  "controls": "タッチ：▲▼◀▶ボタン・めいろを スワイプ・見た マスを タップで そこまで 歩く、✨ボタンで ひかりのたま / キーボード：矢印キー・WASDで いどう、スペースで ひかりのたま / マウス：見た マスを クリックで 歩く",
  "path": "games/064-dark-maze/index.html",
  "cover": "assets/covers/064.webp"
},
{
  "id": "063",
  "title": "ぴょんと雲のうえ",
  "genre": "ACTION",
  "cat": "action",
  "emoji": "🐰",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "ぴょんぴょん はねる うさぎを 左右に うごかして、雲から雲へ 上へ上へ。うごく雲・こわれる雲・ばね・かみなり雲が出てきて、のぼるほど むずかしくなるよ。⭐を10こ あつめると ふうせんが 1回 たすけてくれる。高さベストと★メダルの「どこまでも」、タイムをきそう「300mレース」の2モード。",
  "controls": "タッチ：◀ ▶ ボタン（または がめんの左がわ・右がわ）を おしっぱなし ／ キーボード：← → キー（A・D）、P で ひとやすみ",
  "path": "games/063-cloud-hop/index.html",
  "cover": "assets/covers/063.webp"
},
{
  "id": "062",
  "title": "ことばあて5",
  "genre": "WORD",
  "cat": "word",
  "emoji": "🔤",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "ひみつの 5もじの ことばを 6回までに 当てよう。みずいろは もじも ばしょも 合ってる、きいろは ばしょちがい。日づけで きまる「きょうの1問」と、当てるほど むずかしくなる フリーモード。約390語、ヒント、れんぞく記録つき。",
  "controls": "タッチ：ひらがなの もじばんを タップして「けってい」（゛゜小 で にごった もじ・小さい もじ） / キーボード：ローマ字で 入力、Enterで けってい、BackSpaceで けす",
  "path": "games/062-five-kana/index.html",
  "cover": "assets/covers/062.webp"
},
{
  "id": "061",
  "title": "はやおしバトル",
  "genre": "VERSUS",
  "cat": "versus",
  "emoji": "🔔",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "お題に あう「あいず」が 出た しゅんかんに ボタンを おす 早おしたいせん。お題は いろかたち・えさがし・けいさん・おなじ絵・かぞえて・もじといろ の6しゅるい。おてつきは おやすみ。2〜4人で 5ポイント先取、ひとりなら 3だんかいの CPUと。はんのうタイムと かちまけを きろく。",
  "controls": "タッチ：じぶんの色の ボタンを タップ（同時タッチOK）。キーボード：P1＝A、P2＝L、P3＝Q、P4＝P（ひとりのときは スペースでもOK）。Escで ひとやすみ。",
  "path": "games/061-quick-buzz/index.html",
  "cover": "assets/covers/061.webp"
},
{
  "id": "058",
  "title": "ぷかぷかバブル",
  "genre": "SHOOTING",
  "cat": "shooter",
  "emoji": "🫧",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-06",
  "description": "ねらってバブルをとばし、おなじ色を3つ以上くっつけて消すシューティングパズル。かべのはねかえりで おくもねらえます。天井がだんだん下がる30ステージ（★3つ評価）と、れつがふえるエンドレス。ささえをなくすと まとめて落ちて大ボーナス！",
  "controls": "タッチ・マウス：画面をさわって ねらい、はなすと発射。左下の「つぎ」をタップで色をいれかえ / キーボード：← → で ねらい（Shiftで こまかく）、スペースで発射、↓ で いれかえ、Escで ひとやすみ",
  "path": "games/058-bubble-aim/index.html",
  "cover": "assets/covers/058.webp"
},
{
  "id": "057",
  "title": "くろタイルタップ",
  "genre": "RHYTHM",
  "cat": "rhythm",
  "emoji": "🎹",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "ながれてくる くろいタイルを 下からじゅんにタップ。たたくたびにメロディが1音ずつ鳴って、曲になるよ。白をふむとライフがへる。オリジナル6曲×3つのむずかしさ、1しゅうごとに速くなり、ならびは毎回かわる。★の記録と、メドレーがどんどん速くなるエンドレスつき。",
  "controls": "4つのレーンを指でタップ（両手OK）。PCは左から D・F・J・K キー、またはクリック。P か Esc でポーズ。",
  "path": "games/057-dark-tile-tap/index.html",
  "cover": "assets/covers/057.webp"
},
{
  "id": "056",
  "title": "すべらせナンバー",
  "genre": "PUZZLE",
  "cat": "puzzle",
  "emoji": "🔢",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "タイルをあきマスへすべらせて、1からじゅんばんにならべるスライドパズル。3×3・4×4・5×5の全9ステージで、もんだいは毎回かわる（かならずとけるならびだけ）。すうじモードと絵がらモード、1もん3回までのヒント、つぎのもくひょう表示、ステージごとの手数・タイムのベストと★、絵のコレクションつき。",
  "controls": "タイルをタップ（あきマスと同じれつは まとめてすべる）・スワイプ / 矢印キー（WASD）でタイルをうごかす、H＝ヒント（1もん3回まで）、M＝みほん、R＝やりなおし、N＝まぜなおす",
  "path": "games/056-slide-number/index.html",
  "cover": "assets/covers/056.webp"
},
{
  "id": "055",
  "title": "どうぶつかぞえっこ",
  "genre": "KIDS",
  "cat": "kids",
  "emoji": "🐰",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "3歳〜",
  "date": "2026-10-02",
  "description": "どうぶつを さわって かぞえ、おなじ かずを えらぶ ちいくゲーム。うごきまわる・かくれんぼ・かけっこ・たしざん など 12の ひろばで、1から 20までの かずに ちょうせん。5もん中 3もん いっかいで あたると ごほうびシール、ぜんぶ あたると きらきらシール。れんぞく せいかいを きそう「ちょうせん」つき。",
  "controls": "タッチ／クリック：どうぶつを さわると かぞえた しるしが つく。したの かずの ボタンで こたえる。キーボード：↑↓で どうぶつを えらんで スペースで さわる、←→で かずを えらんで Enter、または すうじキー。Rで もういちど みる。",
  "path": "games/055-count-animals/index.html",
  "cover": "assets/covers/055.webp"
},
{
  "id": "054",
  "title": "ドットおえかき",
  "genre": "CREATIVE",
  "cat": "creative",
  "emoji": "🎨",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "お手本を見て、おなじドット絵をかくゲーム。そっくり度で★がもらえる「お手本チャレンジ」20種、まいかい絵がかわる「モンスターラッシュ」、16×16・32×32の「じゆうモード」（5まいほぞん）であそべる。バケツ・スポイト・かがみペン・もどす つき。",
  "controls": "タッチ：色とどうぐをえらび、マスをタップ／なぞってぬる。PC：クリックでぬる・右クリックでけす／矢印キー＋スペースでぬる、数字キーで色、Zでもどす、Enterで「できた！」",
  "path": "games/054-dot-paint/index.html",
  "cover": "assets/covers/054.webp"
},
{
  "id": "053",
  "title": "とめっこ しちならべ",
  "genre": "CARD",
  "cat": "card",
  "emoji": "🃏",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "7のとなりから じゅんにカードを出して、手札を先になくした人のかち。パスは3回まで。出せるのに わざとパスして「とめる」かけひきが楽しい七ならべ。性格のちがうCPU3人と3ラウンド勝負。3レベル・トンネルルール・ヒント・成績と しょうごうの記録つき。",
  "controls": "カードをタップでえらび、もういちどタップか「だす」。出せない・とめたい時は「パス」。キーボードは ←→でえらぶ、Enterで出す、Pでパス、Hでヒント。",
  "path": "games/053-sevens-line/index.html",
  "cover": "assets/covers/053.webp"
},
{
  "id": "052",
  "title": "けいさんダッシュ",
  "genre": "BRAIN",
  "cat": "brain",
  "emoji": "🏃",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "けいさんに こたえると キャラがダッシュ、まちがえると つまずく 60びょうレース。ライバルより 遠くまで 走ろう。たし・ひき・かけ・わり・ミックス×3レベルの15コース。れんぞく正解のブーストやターボ、★とベスト記録、かつと強くなるライバル、まちがいリストの れんしゅうつき。",
  "controls": "画面のテンキーをタップして「OK」 / キーボードは すうじキーで うって Enter、Backspaceで けす",
  "path": "games/052-calc-dash/index.html",
  "cover": "assets/covers/052.webp"
},
{
  "id": "051",
  "title": "ほしぞら五目ならべ",
  "genre": "BOARD",
  "cat": "board",
  "emoji": "⚫",
  "color": "#a06bff",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "13×13のばんに石をこうたいでおき、たて・よこ・ななめに先に5つならべたら勝ち。CPUは3段階（つよいは先読みつき）、ふたり対戦もOK。虫めがねと2回タップでおきまちがえにくく、きけんサイン・ヒント・1手もどす、強さ別の成績としょうごうつき。",
  "controls": "タップでえらぶ→もういちどタップ（または「ここにおく」）でおく。ゆびをすべらせると虫めがね / マウスはクリック / やじるしキー＋Enter、Z＝もどす、H＝ヒント",
  "path": "games/051-five-row/index.html",
  "cover": "assets/covers/051.webp"
},
{
  "id": "050",
  "title": "もぐらポン",
  "genre": "ARCADE",
  "cat": "arcade",
  "emoji": "🔨",
  "color": "#ff5fa2",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "あなから出たもぐらをすばやくポン！ ひよことくまさんは、たたいちゃダメ。よく見てつづけて当てるとコンボで点が5ばいまでふえるよ。金のもぐら、2かいたたくヘルメットもぐら、ちらっと出るフェイントも登場。30びょうとエンドレスの2モードで、ベストと★をきろく。",
  "controls": "タップ／クリックで あなを たたく ・ キーボードは Q W E / A S D / Z X C（テンキー1〜9）が 9つのあなに対応、Pで ひとやすみ",
  "path": "games/050-mole-pop/index.html",
  "cover": "assets/covers/050.webp"
},
{
  "id": "049",
  "title": "ひとくちダンジョン",
  "genre": "RPG",
  "cat": "adventure",
  "emoji": "🗡️",
  "color": "#ffd166",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "じぶんが1歩うごくと、てきも1歩うごくターン制のダンジョンたんけん。地図は毎回かわり、けん・くすり・4しゅるいのまきものをつかって、ちか10かいのドラゴンとたからばこをめざす。やさしい・ふつう・むずかしいの3モードで、いちばん深くもぐった階とスコアをきろく。",
  "controls": "タッチ：やじるしボタン／スワイプ／ばめんタップで1歩、「まつ」でその場で1ターン、どうぐボタンでつかう。キーボード：矢印キー・WASDでうごく、スペースでまつ、1〜4でどうぐ、Mでおと",
  "path": "games/049-bite-dungeon/index.html",
  "cover": "assets/covers/049.webp"
},
{
  "id": "048",
  "title": "よるのランナー",
  "genre": "ACTION",
  "cat": "action",
  "emoji": "🏃",
  "color": "#53e0d8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-10-02",
  "description": "夜のまちの やねを 走る ランナーを、ジャンプ・2だんジャンプ・スライドで しょうがいぶつから まもる アクション。だんだん はやくなり、エリアごとに 新しい しかけが 出るよ。あつめた コインで 6しゅるいの きせかえ、3つの ミッション、ベストきょりの きろくつき。",
  "controls": "タッチ：がめんタップ・▲ボタンで ジャンプ（空中で もう1回で 2だんジャンプ）、▼ボタンで スライド / キーボード：スペース・↑で ジャンプ、↓・Sで スライド、Pで ポーズ / マウス：クリックで ジャンプ、右クリックで スライド",
  "path": "games/048-night-runner/index.html",
  "cover": "assets/covers/048.webp"
},
{
  "id": "046",
  "title": "はこはこ倉庫",
  "genre": "SOKOBAN",
  "emoji": "📦",
  "color": "#ddbc86",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "箱を押して、すべてゴールへ運ぼう。押す順番を考える全15面。何回でも1手もどせて、さいたん手数に近いと★3。",
  "controls": "十字ボタン・スワイプ・矢印キーで移動。行きたい床をタップするとそこまで歩きます。Zでもどす、Rでさいしょから。",
  "path": "games/046-hakohako-warehouse/index.html",
  "cover": "assets/covers/046.webp"
},
{
  "id": "045",
  "title": "ドットのひみつ",
  "genre": "NONOGRAM",
  "emoji": "🖼️",
  "color": "#ffc187",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "数字をヒントにマスを塗って、かくれたドット絵を見つけよう。はじめてでも安心の「れんしゅう」つき。5×5・8×8・10×10の全33問。",
  "controls": "タップやなぞってマスを塗る。「× メモ」は塗らないマスのしるし（PCは右クリックでも×）。ぜんぶそろうと自動で絵が完成。",
  "path": "games/045-dot-secret/index.html",
  "cover": "assets/covers/045.webp"
},
{
  "id": "044",
  "title": "ひといきソリティア",
  "genre": "SOLITAIRE",
  "emoji": "♠️",
  "color": "#8ed1b1",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "クロンダイクの1枚めくり。場札は赤黒こうごに大きい順、組札は同じマークでAからKへ。カードをタップすると置ける場所へ自動で動き、ヒント・もどす・詰みのお知らせつき。",
  "controls": "カードをタップで置ける場所へ自動移動（ドラッグでも動かせる）。山札をタップでめくる。もどす・ヒントつき。",
  "path": "games/044-hitoiki-solitaire/index.html",
  "cover": "assets/covers/044.webp"
},
{
  "id": "042",
  "title": "ころころミニゴルフ",
  "genre": "SPORTS",
  "emoji": "⛳",
  "color": "#a3dba8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "ボールをうしろに引っぱって打つミニゴルフ。ななめのかべ・すな・坂・池・かざぐるまがある全9ホールで、ホールインワンをねらおう。",
  "controls": "ボールをうしろに引っぱって はなすと打つ（長く引くほど強い）。PCは矢印キーで向きと強さ、スペースで打つこともできます。",
  "path": "games/042-korokoro-golf/index.html",
  "cover": "assets/covers/042.webp"
},
{
  "id": "041",
  "title": "まよい森の郵便屋",
  "genre": "ADVENTURE",
  "emoji": "✉️",
  "color": "#b0d891",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "森の郵便屋になって道を選ぼう。拾ったものや親切が物語を変える。絵つきの27場面と8つの結末、結末ノートつき。",
  "controls": "選択肢をタップ。持ちものを使う道もあるよ。見つけた結末は「結末ノート」に記録。",
  "path": "games/041-forest-post/index.html",
  "cover": "assets/covers/041.webp"
},
{
  "id": "040",
  "title": "のんびり釣り日和",
  "genre": "FISHING",
  "emoji": "🎣",
  "color": "#82d5ed",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "竿を投げて、浮きがしずんだら合わせよう。動く印を緑のゾーンで止めて釣り上げる。川・海・夜の海で20種類の図鑑とサイズ記録を集めよう。",
  "controls": "「投げる」→浮きがしずんだら「合わせる」→白い印が緑の中で「釣り上げる」。画面タップやスペースキーでもOK。",
  "path": "games/040-nonbiri-fishing/index.html",
  "cover": "assets/covers/040.webp"
},
{
  "id": "038",
  "title": "おやつ防衛隊",
  "genre": "TOWER DEFENSE",
  "emoji": "🍪",
  "color": "#eeb27f",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "虫たちが道をとおって、おやつをねらってくるよ。道のまわりにクマ・ウサギ・ゾウ・ペンギンの守り役をおいて、ぜんぶのウェーブでおやつを守りきればクリア！ 3つのステージ、ボスも登場。",
  "controls": "＋のマスをタップ→下のボタンで守り役をえらぶ。おいた守り役をタップで強化。「ウェーブスタート」で開始。",
  "path": "games/038-oyatsu-defense/index.html",
  "cover": "assets/covers/038.webp"
},
{
  "id": "037",
  "title": "こつこつ工房",
  "genre": "IDLE",
  "emoji": "⚙️",
  "color": "#94d9c0",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "木を切って板・いす・おもちゃに加工して売ろう。機械を増やすと自動で作ってくれて、小さな小屋がだんだん大きな工房に育つよ。累計20000コインで工房マスター！",
  "controls": "「切る」「作る」「売る」をタップ。設備タブで機械や倉庫を強化しよう。",
  "path": "games/037-kotsukotsu-factory/index.html",
  "cover": "assets/covers/037.webp"
},
{
  "id": "036",
  "title": "まめまめカフェ",
  "genre": "MANAGEMENT",
  "emoji": "☕",
  "color": "#f5ca88",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "10日間でカフェを町いちばんのお店にしよう。お客さんの注文を順番にお出しして、毎日の目標で★を集めるよ。設備を買うとメニューが増えるよ。",
  "controls": "注文と同じメニューを左から順にタップ。営業のあとで設備を買えるよ。",
  "path": "games/036-mamemame-cafe/index.html",
  "cover": "assets/covers/036.webp"
},
{
  "id": "035",
  "title": "まんまるペット",
  "genre": "PET",
  "emoji": "🐣",
  "color": "#ffb0cd",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "ごはん・ボール遊び・あわあわおていれでペットを育てよう。たまごから7つの姿に変わり、育て方で3種類のおとなになるよ。ずかんを集めよう。",
  "controls": "お世話ボタンをタップ。ミニゲームはタッチで遊ぶよ。つかれたら「ねる」で休もう。",
  "path": "games/035-marumaru-pet/index.html",
  "cover": "assets/covers/035.webp"
},
{
  "id": "034",
  "title": "小さな部屋のひみつ",
  "genre": "ESCAPE",
  "emoji": "🗝️",
  "color": "#c7afff",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "4つの部屋を調べて、道具と暗号を見つけて脱出しよう。暗号は毎回かわるよ。ヒントは少しずつ出てくるので、ヒントなしの★3をめざそう。",
  "controls": "気になる所をタップで拡大。道具は自動で使われる。暗号はボタンで入力。",
  "path": "games/034-small-room/index.html",
  "cover": "assets/covers/034.webp"
},
{
  "id": "032",
  "title": "トコトコリズム",
  "genre": "RHYTHM",
  "emoji": "🥁",
  "color": "#84dafa",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "流れてくる音符が白い線に来たら左右をタップ。テンポのちがう4曲と3つのむずかしさで、ランクSをめざそう。",
  "controls": "画面の左右半分か下のボタンをタップ。PCは左F・右J。",
  "path": "games/032-tokotoko-rhythm/index.html",
  "cover": "assets/covers/032.webp"
},
{
  "id": "031",
  "title": "ぴったり10",
  "genre": "BRAIN TRAINING",
  "emoji": "🔟",
  "color": "#a4de8b",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "数字をえらんで、もくひょうの数ぴったりにしよう。10から25まで大きくなるステップ12問と、60秒タイムアタックで遊べるよ。",
  "controls": "数字をタップでえらぶ・外す。ぴったりで自動正解。PCは数字キー1〜9でも選べる。",
  "path": "games/031-pittari-ten/index.html",
  "cover": "assets/covers/031.webp"
},
{
  "id": "030",
  "title": "ことば配達便",
  "genre": "TYPING",
  "emoji": "📮",
  "color": "#ffa6b7",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "60秒で いくつ言葉を配達できるかな？ 3つのレベル・150こ以上のお題。ノーミスで届けると+1秒！",
  "controls": "ローマ字で入力（shi/si・tsu/tu・nn・xtu など、どの打ちかたでもOK）。PCキーボード推奨。スマホは英字キーボードか、かな入力でも遊べます。",
  "path": "games/030-kotoba-delivery/index.html",
  "cover": "assets/covers/030.webp"
},
{
  "id": "029",
  "title": "ひらめきクイズ",
  "genre": "QUIZ",
  "emoji": "💡",
  "color": "#ffd278",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "6ジャンル・130問以上の3択クイズ。はやく答えるとボーナス、れんぞく正解でコンボ！ 最後にまちがえた問題をふくしゅうできるよ。",
  "controls": "答えをタップ（PCは1〜3キーでも可）→「つぎへ」。",
  "path": "games/029-hirameki-quiz/index.html",
  "cover": "assets/covers/029.webp"
},
{
  "id": "028",
  "title": "ことば探偵",
  "genre": "WORD",
  "emoji": "🔎",
  "color": "#7ce0c1",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "ひみつの言葉（3もじ/4もじ）を6回以内に当てよう。緑は場所まで正解、黄は場所ちがい。2回まちがえるとヒントが出るよ。",
  "controls": "画面のひらがなキーボードをタップ（゛゜・小でだく音や小さい文字）。PCはローマ字でも打てます。",
  "path": "games/028-kotoba-tantei/index.html",
  "cover": "assets/covers/028.webp"
},

  {
    id: "027",
    genre: "BOARD",
    age: "6歳〜",
    color: "#ffd166",
    title: "くるりんリバーシ",
    emoji: "⚫",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "8×8の盤で相手の石をはさんでひっくり返す定番ボードゲーム。ふたりで交代でも、3段階のCPU（よわい／ふつう／つよい＝先読み探索＋終盤は完全読み）相手でも。置ける場所と返せる枚数のヒント表示、波打つフリップ演出、パス表示、1手もどす、CPUレベル別の成績記録つき。",
    controls: "置きたいマスをタップ / キーボードは矢印キー＋Enter、Z＝もどす、H・N＝ヒント切替",
    path: "games/027-kururin-reversi/index.html",
    cover: "assets/covers/027.webp",
  },
  {
    id: "026",
    genre: "ARCADE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "バウンドブレイカー",
    emoji: "🧱",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "ネオンに光るブロックをボールで全部こわすブロック崩し。全8ステージ＋ループで少しずつスピードアップ、2回当てないと壊れないブロックやこわれない壁も登場。パドル拡大・ボール3分裂・つらぬき・スローの4種のカプセル、コンボ加点、パーティクル演出、ベストスコア記録つき。",
    controls: "ゆびでドラッグ／タップで発射 / キーボードは←→・スペース発射・Pでポーズ",
    path: "games/026-bound-breaker/index.html",
    cover: "assets/covers/026.webp",
  },
  {
    id: "025",
    genre: "LOGIC",
    age: "8歳〜",
    color: "#a06bff",
    title: "ドキドキスイーパー",
    emoji: "💣",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "ネオンに光る格子で遊ぶ地雷探しパズル。数字は「まわり8マスにある地雷の数」、最初の1タップは必ず安全。やさしい（9×9）・ふつう（16×16）・むずかしい（16×30）の3レベルで、レベルごとのベストタイムを記録。数字をタップしてまわりを一気に開く「コード」、波紋のように広がる連鎖オープン、クリア時の花火つき。",
    controls: "タップでひらく・長押しか「はた」モードで旗 / PCは左クリック・右クリックで旗・数字クリックで一括オープン、矢印キー+Enter・F",
    path: "games/025-dokidoki-sweeper/index.html",
    cover: "assets/covers/025.webp",
  },
  {
    id: "024",
    genre: "TILE MATCH",
    age: "6歳〜",
    color: "#ffd166",
    title: "3まいそろえ",
    emoji: "🀄",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "何層にも重なった絵柄タイルを上から取って、下のトレイ（7枠）に集めるじっくりパズル。同じ絵が3枚そろうと弾けて消え、全部消せばクリア。レベルが上がるほど枚数と層が増え（配置は必ず解けるように生成）、道具3種「もどす・シャッフル・3まいだし」で切り抜けよう。タイマーなし、進んだレベルは自動保存。",
    controls: "タイルをタップでトレイへ / キーボードは矢印キーで選んでEnter、Z・S・Dで道具、Rでやりなおし",
    path: "games/024-sanmai-soroe/index.html",
    cover: "assets/covers/024.webp",
  },
  {
    id: "023",
    genre: "SORT PUZZLE",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "いろわけボトル",
    emoji: "🧪",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "まざった色の液体をボトルからボトルへ注いで、ぜんぶ1色4層にそろえるパズル。同じ色の上（か空のボトル）にだけ注げて、続いている分だけいっきに移る。レベルは3色から最大9色まで自動生成（必ず解ける保証つき）。1手もどす無制限・ヒント・レベルごとの最少手数記録・色覚に配慮したマーク付き。",
    controls: "ボトルをタップ→注ぎ先をタップ / PCは1〜9・0キー、矢印＋Enter、Z=もどす、H=ヒント、R=リセット",
    path: "games/023-irowake-bottle/index.html",
    cover: "assets/covers/023.webp",
  },
  {
    id: "022",
    genre: "BLOCK PUZZLE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "ぴたっとブロック",
    emoji: "🧩",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "8×8の盤面に3つのピースをドラッグして置き、タテかヨコの列がそろうと消えるブロックパズル。2列同時消しで「COMBO x2!」、連続で消し続けるとSTREAK加点。ピースは指の上に浮いて見え、置ける場所はゴーストで表示。ベスト記録と盤面は自動セーブされるので途中でやめても続きから遊べる。",
    controls: "ピースを盤面へドラッグ / キーボードは1〜3でピース選択、矢印で移動、Enterで置く",
    path: "games/022-pitatto-block/index.html",
    cover: "assets/covers/022.webp",
  },
  {
    id: "021",
    genre: "TIMING",
    age: "6歳〜",
    color: "#a06bff",
    title: "つみあげタワー",
    emoji: "🏗️",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "左右に往復するブロックをタイミングよく止めて、どこまでも高くつみあげるタイミングゲーム。はみ出た部分は切り落とされて落下し、ブロックはどんどん細く・はやくなる。ぴったり止めればPERFECTで幅が少し回復、コンボが続くほど音が高くなる。虹色に変わるタワーと、ゲームオーバー時の全景ズームアウト、ベスト記録つき。",
    controls: "画面タップ か「つむ！」ボタン / キーボードはスペース・Enter",
    path: "games/021-tsumiage-tower/index.html",
    cover: "assets/covers/021.webp",
  },
  {
    id: "020",
    genre: "ONE BUTTON",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "トントンふくろう",
    emoji: "🦉",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "タップで小さなフクロウが羽ばたく1ボタン飛行ゲーム。上下からのびるネオン柱のすき間をくぐりぬけて1点、柱・地面・天井にぶつかったらおしまい。進むほどすき間がせまく速くなり、10点ごとに夜の色がかわって流れ星が降る。夜空・月・流れる街並みの多層背景、ベスト記録と10・25・50点のメダルつき。",
    controls: "画面をタップで羽ばたく / キーボードはスペース・↑・Enter、Pでポーズ",
    path: "games/020-tonton-fukurou/index.html",
    cover: "assets/covers/020.webp",
  },
  {
    id: "019",
    genre: "ARCADE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "ぐんぐんスネーク",
    emoji: "🐍",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "光るヘビを操作してエサを食べ、どんどん長くなるアーケード。全8ステージのステージモードと、かべあり・ワープのハイスコアモード。スローやすりぬけの とくべつなエサも出るよ。",
    controls: "スワイプ か 十字ボタン ／ 矢印キー・WASD、Pでポーズ",
    path: "games/019-gungun-snake/index.html",
    cover: "assets/covers/019.webp",
  },
  {
    id: "018",
    genre: "NUMBER PUZZLE",
    age: "6歳〜",
    color: "#ffd166",
    title: "そろえて2048",
    emoji: "🔢",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "4×4のマスでタイルをすべらせ、同じ数字をぶつけて合体させる定番の数字パズル。2048を作ったらクリア、そのあとも続けてハイスコアを狙える。数字が大きいほど光って音も高くなり、2048達成で紙吹雪。ベスト記録と途中の盤面は自動セーブ、1手もどす機能つき。",
    controls: "上下左右にスワイプ / キーボードは矢印キー・WASD、Zで1手もどす",
    path: "games/018-soroete-2048/index.html",
    cover: "assets/covers/018.webp",
  },
  {
    id: "017",
    genre: "CARD GAME",
    age: "8歳〜",
    color: "#ffd166",
    title: "よふかし大富豪",
    emoji: "🃏",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "CPU3人と対戦する定番トランプゲーム。8切り・革命・階段・縛り・11バック・都落ち・禁止上がり・カード交換などのローカルルールを設定画面でON/OFFできる。迷ったら「おすすめ」ボタン。",
    controls: "カードをタップして「出す」か「パス」 / PCはEnter・P・H",
    path: "games/017-yofukashi-daifugo/index.html",
    cover: "assets/covers/017.webp",
  },
  {
    id: "016",
    genre: "2P BATTLE",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "ぬりぬりバトル",
    emoji: "🎨",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "60秒で床を自分の色に塗りまくる陣取りバトル。相手の色の上も塗り替えOK、ペイントボムとダッシュで逆転を狙え。ひとつの画面をふたりで取り合うか、CPUと対戦。",
    controls: "2人用!タッチは上下半分をドラッグ（スティック） / キーボードはWASD・矢印キー",
    path: "games/016-nurinuri-battle/index.html",
    cover: "assets/covers/016.webp",
  },
  {
    id: "015",
    genre: "BOARD",
    age: "6歳〜",
    color: "#ffd166",
    title: "よふかし四目ならべ",
    emoji: "🔵",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "コマを上から落として、タテ・ヨコ・ナナメに4つならべたら勝ちの定番ボードゲーム。ふたりで交代でも、3段階のCPU（よわい／ふつう／つよい）相手でも。落下アニメ・1手もどす・成績記録つき。",
    controls: "落としたい列をタップ / キーボードは1〜7、←→＋Enter",
    path: "games/015-yofukashi-connect4/index.html",
    cover: "assets/covers/015.webp",
  },
  {
    id: "014",
    genre: "2P BATTLE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "ネオンサイクル",
    emoji: "🏍️",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "光の線をのばして相手を囲む対戦ライトサイクル。ブロック・ワープ・せまるカベの3ステージで3本先取、⚡をとるとブーストがすぐたまる。CPUは3段階。",
    controls: "スマホ：スワイプで方向転換、2回タップか⚡ボタンでブースト（ふたりのときは上半分・下半分で分担）／PC：P1はWASD＋F、P2は矢印＋Enter（CPU戦は矢印でもOK）",
    path: "games/014-neon-cycle/index.html",
    cover: "assets/covers/014.webp",
  },
  {
    id: "013",
    genre: "CASINO",
    age: "15歳〜",
    color: "#ffd166",
    title: "よふかしバカラ",
    emoji: "🃏",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "韓国カジノのノーコミッション卓ルール（バンカー1倍・6で勝ちは半額、タイ8倍、ペア11倍）で遊ぶ架空マネーのバカラ。持ち金100万円を1,000万円まで増やせたらクリア。しぼり・珠盤路・大路つき。",
    controls: "チップを選んでベット枠をタップ→DEAL / PCはEnterでDEAL",
    path: "games/013-yofukashi-baccarat/index.html",
    cover: "assets/covers/013.webp",
  },
  // ---- 未公開（公開判断待ち）----------------------------------------------
  // 012「シンプルシューティングR」は2026-08-27にローカル制作、本番サイト未反映。
  // 公開OKが出たら下のブロックのコメントを外し、games/012-simple-shooting-r/ をGitHubへアップする。
  /*
  {
    id: "012",
    genre: "SHOOTING",
    age: "9歳〜",
    color: "#3fe0dc",
    title: "シンプルシューティングR",
    emoji: "🚀",
    author: "スタッフ", // 公開時に作者ニックネームを入れる
    date: "2026-08-27",
    description:
      "5しゅるいの てきと 5ウェーブごとのボスがくる たてスクロールシューティング。パワーアップ・ボム・コンボでハイスコアをめざそう！",
    controls: "PC：やじるしキーでいどう、スペースでショット、Xでボム、Pでポーズ。スマホ：ドラッグでいどう（じどうでうつ）、下のボタンでボム・ポーズ。",
    path: "games/012-simple-shooting-r/index.html",
  },
  */
  // --------------------------------------------------------------------------
  {
    id: "011",
    genre: "2P BATTLE",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "よふかしホッケー",
    emoji: "🏒",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "光るパックをはじき合うエアホッケー。CPUと3つのつよさで対戦できるほか、1台をふたりで取り合う対戦も。先に5点とったほうの勝ち！",
    controls: "ひとりで：画面をドラッグ（どこを触ってもOK）、PCはマウスかWASD/矢印キー。ふたりで：うえの人はうえ半分・したの人はした半分をドラッグ、キーボードは した=WASD／うえ=矢印キー。",
    path: "games/011-yofukashi-hockey/index.html",
    cover: "assets/covers/011.webp",
  },
  {
    id: "010",
    genre: "MINI RPG",
    age: "8歳〜",
    color: "#8f7bff",
    title: "よふかしクエスト",
    emoji: "⚔️",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "草むらで戦ってレベルを上げ、洞窟の「よるのおう」に挑む小さなRPG。ひっさつ技・そうび・かくしボスの塔もあって、クリア後もぼうけんが続くよ。",
    controls: "矢印キー/WASDかDパッドでいどう、Z・Enter・スペースかAボタンで はなす・しらべる・すすめる。せんとうはボタンをタップ（キーなら←→でえらんでZ）。",
    path: "games/010-yofukashi-quest/index.html",
    cover: "assets/covers/010.webp",
  },
  {
    id: "009",
    genre: "FIXED SHOOTER",
    age: "7歳〜",
    color: "#7dff6a",
    title: "よふかしインベーダー",
    emoji: "👾",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "夜の街にせまるUFO軍団をうち落とすシューティング。パワーアップカプセルや4ウェーブごとのボスUFOが登場。「やさしい」モードなら小さい子もあんしん。",
    controls: "PC：←→（A/D）でうごく、スペースでうつ、Pでいちじていし。スマホ：画面を指でなぞるといどう＆じどうれんしゃ（下のボタンでもOK）",
    path: "games/009-yofukashi-invader/index.html",
    cover: "assets/covers/009.webp",
  },
  {
    id: "008",
    genre: "FALLING PUZZLE",
    age: "7歳〜",
    color: "#53e0d8",
    title: "ネオンフォール",
    emoji: "🧱",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "ネオンのブロックをそろえて消す落ちものパズル。ホールドやれんさボーナスつきで、エンドレス・全15ステージ・40ラインの3つのモードで遊べる。",
    controls: "PC：←→でいどう、↑/Z/Xでかいてん、↓でちょっとおとす、スペースでいっきにおとす、C/Shiftでホールド、Pでいちじていし。スマホ：下のボタン、またはばんめんをタップでかいてん・ヨコにスライドでいどう・下にはらうといっきにおとす・上にはらうとホールド",
    path: "games/008-neon-fall/index.html",
    cover: "assets/covers/008.webp",
  },
  {
    id: "007",
    color: "#4f91c7",
    genre: "ANIMAL MERGE",
    age: "6歳〜",
    title: "よふかしアニマル",
    emoji: "🐘",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "同じ動物を合体させると、もっと大きくて強い動物へ進化。ひよこから始めて、最後のゾウを目指す動物マージパズル。",
    controls: "ねらって、はなすと落ちる（タップ / クリック）",
    path: "games/007-yofukashi-suika/index.html",
    cover: "assets/covers/007.webp",
  },
  {
    id: "006",
    genre: "BOSS RUSH",
    age: "10歳〜",
    color: "#ffe14d",
    title: "コラムブレイカー",
    emoji: "⚡",
    author: "ゲスト",
    date: "2026-08-20",
    description:
      "縦レーザーで挑むボスラッシュ5連戦。ボスの真下にいつづけるとねらいうちされるので、左右にゆれながらコアをねらおう。かんたん・ふつう・むずかしいの3段階とランク評価つき。",
    controls: "PC：WASD/矢印でいどう、スペース/クリック長おしでレーザー、Shiftでしゅうちゅう、Pでポーズ。スマホ：ドラッグでいどう、左下FIREでレーザー、右下FOCUSでしゅうちゅう（タイトルで「さわってる間うつ」にも切りかえ可）",
    path: "games/006-column-breaker/index.html",
    cover: "assets/covers/006.webp",
  },
  {
    id: "005",
    genre: "PUZZLE SHOT",
    age: "8歳〜",
    color: "#ff4d6d",
    title: "リコシェ・ワン",
    emoji: "🎯",
    author: "スタッフ",
    date: "2026-08-20",
    description:
      "壁に跳ね返る弾で隠れた的を撃ち抜くパズルシューティング。ワープ・重力・動く壁——仕掛けだらけの全10ステージ。",
    controls: "マウスで狙ってクリック / 指でなぞって離す",
    path: "games/005-ricochet-one/index.html",
    cover: "assets/covers/005.webp",
  },
  {
    id: "004",
    genre: "ARENA SHOOTER",
    age: "10歳〜",
    color: "#ff7a3d",
    title: "アーセナル10",
    emoji: "💥",
    author: "ゲスト",
    date: "2026-08-20",
    description:
      "10種の武器を切り替えて敵の波を迎え撃つアリーナシューティング。ウェーブを重ねて武器を解放し、ボスを撃破せよ。",
    controls: "WASD＋マウス / スマホは左右スティック",
    path: "games/004-arsenal-10/index.html",
    cover: "assets/covers/004.webp",
  },
  {
    id: "003",
    genre: "SHOOTER",
    age: "7歳〜",
    color: "#3dd6ff",
    title: "マーライオンシューター",
    emoji: "🦁",
    author: "スタッフ",
    date: "2026-08-19",
    description:
      "マーライオンの水でっぽうで、夜のシンガポールにふってくるドリアンをうちおとそう。ウェーブごとに強くなり、4ウェーブごとにボスが登場！",
    controls: "←→キー / マウス / ゆびでスライド（ゆびの真上に水がとぶ）",
    path: "games/003-merlion-shooter/index.html",
    cover: "assets/covers/003.webp",
  },
  {
    id: "002",
    genre: "MEMORY",
    age: "6歳〜",
    color: "#b06bff",
    title: "よふかしペアさがし",
    emoji: "👻",
    author: "スタッフ",
    date: "2026-08-19",
    description:
      "カードをめくって同じ絵のペアをさがそう。かんたん・ふつう・むずかしいから選べて、少ない回数でそろえると⭐がふえるよ。",
    controls: "タップ / クリックでむずかしさを選んで、カードを2まいずつめくる",
    path: "games/002-pair-match/index.html",
    cover: "assets/covers/002.webp",
  },
  {
    id: "001",
    genre: "ACTION",
    age: "6歳〜",
    color: "#ff6fa8",
    title: "はなびらキャッチ",
    emoji: "🌸",
    author: "スタッフ",
    date: "2026-08-19",
    description:
      "夜空から降る花をかごでキャッチ！つづけて取るとコンボで点数アップ、とけいで時間をのばし、じしゃくで花をあつめよう。",
    controls: "←→キー / マウス / スワイプ",
    path: "games/001-hanabira-catch/index.html",
    cover: "assets/covers/001.webp",
  },
];
