// ============================================================
// ピコットゲームズ：ゲーム登録リスト
// ------------------------------------------------------------
// 新しいゲームを公開するときは、この配列の一番上に
// 下のような形で1ブロック追加するだけでOK！
//
// {
//   id: "007",                          // 3けたの通し番号
//   title: "ゲームのなまえ",
//   emoji: "🎮",                        // カードに大きく出る絵文字
//   color: "#3ff2e6",                   // カードのテーマカラー（省略可）
//   genre: "ACTION",                    // ジャンル表記（省略可）
//   age: "6歳〜",                       // 対象年齢の目安
//   author: "ニックネーム",              // 本名は書かない！
//   date: "2026-08-27",                 // 公開日
//   description: "どんなゲームか1〜2文で。",
//   controls: "そうさ方法をかんたんに",
//   path: "games/007-xxxx/index.html",  // ゲーム本体の場所
// },
// ============================================================

const GAMES = [
{
  "id": "047",
  "title": "つないで水道",
  "genre": "PIPE PUZZLE",
  "emoji": "🚰",
  "color": "#8aceff",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "パイプを回して、左上の入口から右下の出口までつなごう。つながったパイプは水色になるよ。全8面。",
  "controls": "パイプをタップで90度回転。「水を流す」で確認。",
  "path": "games/047-tsunaide-water/index.html"
},
{
  "id": "046",
  "title": "はこはこ倉庫",
  "genre": "SOKOBAN",
  "emoji": "📦",
  "color": "#ddbc86",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "箱をすべて丸いゴールへ押そう。箱は引っぱれないので壁際に注意。全8面、もどす回数は無制限。",
  "controls": "矢印キー・画面の方向ボタンで移動。Zで1手もどす。",
  "path": "games/046-hakohako-warehouse/index.html"
},
{
  "id": "045",
  "title": "ドットのひみつ",
  "genre": "NONOGRAM",
  "emoji": "🖼️",
  "color": "#ffc187",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "行と列の数字は連続する塗りマスの数。複数ある場合は間に1マス以上あけよう。5×5の全8問。",
  "controls": "タップで塗る。「×をつける」モードで空白をメモ。",
  "path": "games/045-dot-secret/index.html"
},
{
  "id": "044",
  "title": "ひといきソリティア",
  "genre": "SOLITAIRE",
  "emoji": "♠️",
  "color": "#8ed1b1",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "クロンダイクの1枚めくり。場札は赤黒交互に大きい順、組札は同じマークでAからKへ。空の列にはKだけ置けるよ。",
  "controls": "移したいカード→移動先をタップ。山札でめくる。もどす・ヒントつき。",
  "path": "games/044-hitoiki-solitaire/index.html"
},
{
  "id": "043",
  "title": "ストライク広場",
  "genre": "SPORTS",
  "emoji": "🎳",
  "color": "#c6b3ff",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "立ち位置と角度を選んで10本のピンを倒そう。ストライク・スペアのボーナス付き、10フレームのボウリング。",
  "controls": "位置・角度のスライダーを調整して「投げる」。",
  "path": "games/043-strike-square/index.html"
},
{
  "id": "042",
  "title": "ころころミニゴルフ",
  "genre": "SPORTS",
  "emoji": "⛳",
  "color": "#a3dba8",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "方向と強さを決めてボールを打とう。壁に反射する全9ホール。少ない打数でクリアを目指そう。",
  "controls": "スライダーで方向・強さを調整して「打つ」。",
  "path": "games/042-korokoro-golf/index.html"
},
{
  "id": "041",
  "title": "まよい森の郵便屋",
  "genre": "ADVENTURE",
  "emoji": "✉️",
  "color": "#b0d891",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "森の郵便屋になって道を選ぼう。拾ったものや親切が結末を変える短い物語。4つのエンディングつき。",
  "controls": "選択肢をタップ。読んだ結末はブラウザ内に記録。",
  "path": "games/041-forest-post/index.html"
},
{
  "id": "040",
  "title": "のんびり釣り日和",
  "genre": "FISHING",
  "emoji": "🎣",
  "color": "#82d5ed",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "竿を投げ、魚がかかったら合わせよう。動く印を緑のゾーンで止めると釣り成功。6種類の図鑑を集めよう。",
  "controls": "「投げる」→合図で「合わせる」→緑の位置で「釣り上げる」。",
  "path": "games/040-nonbiri-fishing/index.html"
},
{
  "id": "039",
  "title": "くるくるカート",
  "genre": "RACING",
  "emoji": "🏎️",
  "color": "#ff9a91",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "四角い周回コースを3周しよう。コース外では減速。矢印で進行方向を選び、通過ゲートを順番に巡るタイムアタック。",
  "controls": "矢印キーまたは画面の方向ボタン。カートは自動で走ります。",
  "path": "games/039-kurukuru-kart/index.html"
},
{
  "id": "038",
  "title": "おやつ防衛隊",
  "genre": "TOWER DEFENSE",
  "emoji": "🍪",
  "color": "#eeb27f",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "道の周りに守り役を配置。敵を倒して得たコインで増設・強化し、全8ウェーブからおやつを守ろう。",
  "controls": "設置マスをタップ。設置50コイン、強化40コイン。「次のウェーブ」で開始。",
  "path": "games/038-oyatsu-defense/index.html"
},
{
  "id": "037",
  "title": "こつこつ工房",
  "genre": "IDLE",
  "emoji": "⚙️",
  "color": "#94d9c0",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "材料を集めて製品を作り、売上で採集機と加工機を増やそう。金貨1000枚で工房マスター。最大8時間の留守中生産つき。",
  "controls": "採集・加工・販売・設備購入をタップ。進行はブラウザ内に保存。",
  "path": "games/037-kotsukotsu-factory/index.html"
},
{
  "id": "036",
  "title": "まめまめカフェ",
  "genre": "MANAGEMENT",
  "emoji": "☕",
  "color": "#f5ca88",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "注文に合わせて飲み物・おやつを順番に提供。1営業60秒。売上で設備を増やすと1注文の売上が上がるよ。",
  "controls": "注文と同じメニューをタップ。営業の間に設備を購入できます。",
  "path": "games/036-mamemame-cafe/index.html"
},
{
  "id": "035",
  "title": "まんまるペット",
  "genre": "PET",
  "emoji": "🐣",
  "color": "#ffb0cd",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "ごはん・遊び・お手入れでペットを育てよう。お世話で成長して姿が変わるよ。ブラウザ内に自動保存。",
  "controls": "お世話ボタンをタップ。時間がたつと体力が回復します。",
  "path": "games/035-marumaru-pet/index.html"
},
{
  "id": "034",
  "title": "小さな部屋のひみつ",
  "genre": "ESCAPE",
  "emoji": "🗝️",
  "color": "#c7afff",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "部屋を調べて道具と暗号を見つけ、鍵を手に入れて脱出しよう。使う道具は自動で選ばれるよ。",
  "controls": "調べたい場所をタップ。数字の暗号は入力して確認。",
  "path": "games/034-small-room/index.html"
},
{
  "id": "033",
  "title": "ちがいはどこ？",
  "genre": "SPOT DIFFERENCE",
  "emoji": "👀",
  "color": "#ffbd81",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "左右の絵柄を見比べて、右側の違うマスを5つ見つけよう。全3ラウンド、時間制限なし。",
  "controls": "右側の絵柄をタップ。ヒントは各ラウンド1回。",
  "path": "games/033-chigai-doko/index.html"
},
{
  "id": "032",
  "title": "トコトコリズム",
  "genre": "RHYTHM",
  "emoji": "🥁",
  "color": "#84dafa",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "流れてくる音符が白い線に来たら左右のボタンを押そう。正確に押すと100点。オリジナルの短い電子音で遊べるよ。",
  "controls": "左はF、右はJ。スマホは左右のボタン。音のON/OFFつき。",
  "path": "games/032-tokotoko-rhythm/index.html"
},
{
  "id": "031",
  "title": "ぴったり10",
  "genre": "BRAIN TRAINING",
  "emoji": "🔟",
  "color": "#a4de8b",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "9個の数字から合計10になる組み合わせを探そう。時間制限なしの全10問。2個以上の数字を選べるよ。",
  "controls": "数字をタップで選択・解除。「これで10！」で答える。",
  "path": "games/031-pittari-ten/index.html"
},
{
  "id": "030",
  "title": "ことば配達便",
  "genre": "TYPING",
  "emoji": "📮",
  "color": "#ffa6b7",
  "author": "スタッフ",
  "age": "8歳〜",
  "date": "2026-09-13",
  "description": "60秒間でいくつ配達できるかな？ 表示されたローマ字をそのまま入力。最初の入力から計測が始まるよ。",
  "controls": "PCキーボード推奨。半角英数で入力。スマホの英字キーボードでも遊べます。",
  "path": "games/030-kotoba-delivery/index.html"
},
{
  "id": "029",
  "title": "ひらめきクイズ",
  "genre": "QUIZ",
  "emoji": "💡",
  "color": "#ffd278",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "動物・ことば・暮らしの3択クイズ。20問からランダムに10問出題。答えたあとに解説が読めるよ。",
  "controls": "答えをタップして「次の問題へ」。",
  "path": "games/029-hirameki-quiz/index.html"
},
{
  "id": "028",
  "title": "ことば探偵",
  "genre": "WORD",
  "emoji": "🔎",
  "color": "#7ce0c1",
  "author": "スタッフ",
  "age": "6歳〜",
  "date": "2026-09-13",
  "description": "ひらがな3文字の言葉を6回以内に当てよう。緑は場所まで正解、黄は場所違い。困ったらヒントを見てね。",
  "controls": "文字入力＋「答える」。PC・スマホ対応。",
  "path": "games/028-kotoba-tantei/index.html"
},

  {
    id: "027",
    genre: "BOARD",
    age: "6歳〜",
    color: "#ffd166",
    title: "くるりんリバーシ",
    emoji: "⚫",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "8×8の盤で相手の石をはさんでひっくり返す定番ボードゲーム。ふたりで交代でも、3段階のCPU（よわい／ふつう／つよい＝先読み探索＋終盤は完全読み）相手でも。置ける場所と返せる枚数のヒント表示、波打つフリップ演出、パス表示、1手もどす、CPUレベル別の成績記録つき。",
    controls: "置きたいマスをタップ / キーボードは矢印キー＋Enter、Z＝もどす、H・N＝ヒント切替",
    path: "games/027-kururin-reversi/index.html",
  },
  {
    id: "026",
    genre: "ARCADE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "バウンドブレイカー",
    emoji: "🧱",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "ネオンに光るブロックをボールで全部こわすブロック崩し。全8ステージ＋ループで少しずつスピードアップ、2回当てないと壊れないブロックやこわれない壁も登場。パドル拡大・ボール3分裂・つらぬき・スローの4種のカプセル、コンボ加点、パーティクル演出、ベストスコア記録つき。",
    controls: "ゆびでドラッグ／タップで発射 / キーボードは←→・スペース発射・Pでポーズ",
    path: "games/026-bound-breaker/index.html",
  },
  {
    id: "025",
    genre: "LOGIC",
    age: "8歳〜",
    color: "#a06bff",
    title: "ドキドキスイーパー",
    emoji: "💣",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "ネオンに光る格子で遊ぶ地雷探しパズル。数字は「まわり8マスにある地雷の数」、最初の1タップは必ず安全。やさしい（9×9）・ふつう（16×16）・むずかしい（16×30）の3レベルで、レベルごとのベストタイムを記録。数字をタップしてまわりを一気に開く「コード」、波紋のように広がる連鎖オープン、クリア時の花火つき。",
    controls: "タップでひらく・長押しか「はた」モードで旗 / PCは左クリック・右クリックで旗・数字クリックで一括オープン、矢印キー+Enter・F",
    path: "games/025-dokidoki-sweeper/index.html",
  },
  {
    id: "024",
    genre: "TILE MATCH",
    age: "6歳〜",
    color: "#ffd166",
    title: "3まいそろえ",
    emoji: "🀄",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "何層にも重なった絵柄タイルを上から取って、下のトレイ（7枠）に集めるじっくりパズル。同じ絵が3枚そろうと弾けて消え、全部消せばクリア。レベルが上がるほど枚数と層が増え（配置は必ず解けるように生成）、道具3種「もどす・シャッフル・3まいだし」で切り抜けよう。タイマーなし、進んだレベルは自動保存。",
    controls: "タイルをタップでトレイへ / キーボードは矢印キーで選んでEnter、Z・S・Dで道具、Rでやりなおし",
    path: "games/024-sanmai-soroe/index.html",
  },
  {
    id: "023",
    genre: "SORT PUZZLE",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "いろわけボトル",
    emoji: "🧪",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "まざった色の液体をボトルからボトルへ注いで、ぜんぶ1色4層にそろえるパズル。同じ色の上（か空のボトル）にだけ注げて、続いている分だけいっきに移る。レベルは3色から最大9色まで自動生成（必ず解ける保証つき）。1手もどす無制限・ヒント・レベルごとの最少手数記録・色覚に配慮したマーク付き。",
    controls: "ボトルをタップ→注ぎ先をタップ / PCは1〜9・0キー、矢印＋Enter、Z=もどす、H=ヒント、R=リセット",
    path: "games/023-irowake-bottle/index.html",
  },
  {
    id: "022",
    genre: "BLOCK PUZZLE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "ぴたっとブロック",
    emoji: "🧩",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "8×8の盤面に3つのピースをドラッグして置き、タテかヨコの列がそろうと消えるブロックパズル。2列同時消しで「COMBO x2!」、連続で消し続けるとSTREAK加点。ピースは指の上に浮いて見え、置ける場所はゴーストで表示。ベスト記録と盤面は自動セーブされるので途中でやめても続きから遊べる。",
    controls: "ピースを盤面へドラッグ / キーボードは1〜3でピース選択、矢印で移動、Enterで置く",
    path: "games/022-pitatto-block/index.html",
  },
  {
    id: "021",
    genre: "TIMING",
    age: "6歳〜",
    color: "#a06bff",
    title: "つみあげタワー",
    emoji: "🏗️",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "左右に往復するブロックをタイミングよく止めて、どこまでも高くつみあげるタイミングゲーム。はみ出た部分は切り落とされて落下し、ブロックはどんどん細く・はやくなる。ぴったり止めればPERFECTで幅が少し回復、コンボが続くほど音が高くなる。虹色に変わるタワーと、ゲームオーバー時の全景ズームアウト、ベスト記録つき。",
    controls: "画面タップ か「つむ！」ボタン / キーボードはスペース・Enter",
    path: "games/021-tsumiage-tower/index.html",
  },
  {
    id: "020",
    genre: "ONE BUTTON",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "トントンふくろう",
    emoji: "🦉",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "タップで小さなフクロウが羽ばたく1ボタン飛行ゲーム。上下からのびるネオン柱のすき間をくぐりぬけて1点、柱・地面・天井にぶつかったらおしまい。進むほどすき間がせまく速くなり、10点ごとに夜の色がかわって流れ星が降る。夜空・月・流れる街並みの多層背景、ベスト記録と10・25・50点のメダルつき。",
    controls: "画面をタップで羽ばたく / キーボードはスペース・↑・Enter、Pでポーズ",
    path: "games/020-tonton-fukurou/index.html",
  },
  {
    id: "019",
    genre: "ARCADE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "ぐんぐんスネーク",
    emoji: "🐍",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "光るヘビを操作してエサを食べ、どんどん長くなる定番アーケード。食べるほど少しずつ速くなり、たまに出る点滅ボーナス★は時間内に取ると50点。壁で終わる「かべあり」と反対側から出てくる「ワープ」の2モード、ベスト記録は自動保存。",
    controls: "スワイプ or 画面下の十字ボタン / 矢印キー・WASD、Pでポーズ",
    path: "games/019-gungun-snake/index.html",
  },
  {
    id: "018",
    genre: "NUMBER PUZZLE",
    age: "6歳〜",
    color: "#ffd166",
    title: "そろえて2048",
    emoji: "🔢",
    author: "スタッフ",
    date: "2026-09-13",
    description:
      "4×4のマスでタイルをすべらせ、同じ数字をぶつけて合体させる定番の数字パズル。2048を作ったらクリア、そのあとも続けてハイスコアを狙える。数字が大きいほど光って音も高くなり、2048達成で紙吹雪。ベスト記録と途中の盤面は自動セーブ、1手もどす機能つき。",
    controls: "上下左右にスワイプ / キーボードは矢印キー・WASD、Zで1手もどす",
    path: "games/018-soroete-2048/index.html",
  },
  {
    id: "017",
    genre: "CARD GAME",
    age: "8歳〜",
    color: "#ffd166",
    title: "よふかし大富豪",
    emoji: "🃏",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "CPU3人と対戦する定番トランプゲーム。8切り・革命・階段・縛り・11バック・都落ち・禁止上がり・カード交換などのローカルルールを設定画面でON/OFFできる。迷ったら「おすすめ」ボタン。",
    controls: "カードをタップして「出す」か「パス」 / PCはEnter・P・H",
    path: "games/017-yofukashi-daifugo/index.html",
  },
  {
    id: "016",
    genre: "2P BATTLE",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "ぬりぬりバトル",
    emoji: "🎨",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "60秒で床を自分の色に塗りまくる陣取りバトル。相手の色の上も塗り替えOK、ペイントボムとダッシュで逆転を狙え。ひとつの画面をふたりで取り合うか、CPUと対戦。",
    controls: "2人用!タッチは上下半分をドラッグ（スティック） / キーボードはWASD・矢印キー",
    path: "games/016-nurinuri-battle/index.html",
  },
  {
    id: "015",
    genre: "BOARD",
    age: "6歳〜",
    color: "#ffd166",
    title: "よふかし四目ならべ",
    emoji: "🔵",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "コマを上から落として、タテ・ヨコ・ナナメに4つならべたら勝ちの定番ボードゲーム。ふたりで交代でも、3段階のCPU（よわい／ふつう／つよい）相手でも。落下アニメ・1手もどす・成績記録つき。",
    controls: "落としたい列をタップ / キーボードは1〜7、←→＋Enter",
    path: "games/015-yofukashi-connect4/index.html",
  },
  {
    id: "014",
    genre: "2P BATTLE",
    age: "6歳〜",
    color: "#53e0d8",
    title: "ネオンサイクル",
    emoji: "🏍️",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "光の線をのばして相手を囲む対戦ライトサイクル。線・壁・ブロックにぶつかったら負け、先に3ラウンド取れば勝ち。ゲージがたまればブーストで一気に加速。ひとりならCPU対戦（つよいCPUも）。",
    controls: "2人用!タッチは上下半分をスワイプ＋2回タップでブースト / キーボードはWASD＋F・矢印＋Enter",
    path: "games/014-neon-cycle/index.html",
  },
  {
    id: "013",
    genre: "CASINO",
    age: "15歳〜",
    color: "#ffd166",
    title: "よふかしバカラ",
    emoji: "🃏",
    author: "スタッフ",
    date: "2026-09-05",
    description:
      "韓国カジノのノーコミッション卓ルール（バンカー1倍・6で勝ちは半額、タイ8倍、ペア11倍）で遊ぶ架空マネーのバカラ。持ち金100万円を1,000万円まで増やせたらクリア。しぼり・珠盤路・大路つき。",
    controls: "チップを選んでベット枠をタップ→DEAL / PCはEnterでDEAL",
    path: "games/013-yofukashi-baccarat/index.html",
  },
  // ---- 未公開（公開判断待ち）----------------------------------------------
  // 012「シンプルシューティングR」は2026-08-27にローカル制作、本番サイト未反映。
  // 公開OKが出たら下のブロックのコメントを外し、games/012-simple-shooting-r/ をGitHubへアップする。
  /*
  {
    id: "012",
    genre: "SHOOTING",
    age: "9歳〜",
    color: "#3fe0dc",
    title: "シンプルシューティングR",
    emoji: "🚀",
    author: "利用者さん",
    date: "2026-08-27",
    description:
      "敵5種＋ウェーブ制＋ボス戦の本格縦スクロールシューティング。当たり判定は機体中央の点だけだから弾幕もすり抜けられる。コンボをつないで最大×4のスコアを狙え。",
    controls: "矢印キー＋スペース、Xでボム / スマホはドラッグ＋自動連射",
    path: "games/012-simple-shooting-r/index.html",
  },
  */
  // --------------------------------------------------------------------------
  {
    id: "011",
    genre: "2P BATTLE",
    age: "6歳〜",
    color: "#ff5fa2",
    title: "よふかしホッケー",
    emoji: "🏒",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "ひとつの画面をふたりで取り合う対戦エアホッケー。光るパックを弾き合い、先に5点取ったほうが勝ち。ラリーが続くほどパックは加速する。",
    controls: "2人用!タッチは画面を上下で分けてドラッグ / キーボードはWASDと矢印キー",
    path: "games/011-yofukashi-hockey/index.html",
  },
  {
    id: "010",
    genre: "MINI RPG",
    age: "8歳〜",
    color: "#8f7bff",
    title: "よふかしクエスト",
    emoji: "⚔️",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "草むらで戦ってレベルを上げ、洞窟にすむ「よるのおう」に挑む小さなRPG。宝箱・ポーション・セーブつき、クリアまで約15分の冒険。",
    controls: "矢印キー＋Zキー / スマホはDパッド＋Aボタン",
    path: "games/010-yofukashi-quest/index.html",
  },
  {
    id: "009",
    genre: "FIXED SHOOTER",
    age: "7歳〜",
    color: "#7dff6a",
    title: "よふかしインベーダー",
    emoji: "👾",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "夜の街に迫るUFO軍団を撃ち落とす固定画面シューティング。緑の盾に隠れつつ、金のUFOでボーナス。ウェーブは進むほど速く、激しく。",
    controls: "←→＋スペース / スマホは指でなぞって自動連射",
    path: "games/009-yofukashi-invader/index.html",
  },
  {
    id: "008",
    genre: "FALLING PUZZLE",
    age: "7歳〜",
    color: "#53e0d8",
    title: "ネオンフォール",
    emoji: "🧱",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "ネオンのブロックを積み、ヨコ1列そろえて消す落ちものパズル。落下地点のゴースト表示つきで初めてでも遊びやすい。10ラインごとに加速。",
    controls: "←→↓＋↑で回転、スペースで一気に落とす / スマホはボタン",
    path: "games/008-neon-fall/index.html",
  },
  {
    id: "007",
    color: "#4f91c7",
    genre: "ANIMAL MERGE",
    age: "6歳〜",
    title: "よふかしアニマル",
    emoji: "🐘",
    author: "スタッフ",
    date: "2026-08-21",
    description:
      "同じ動物を合体させると、もっと大きくて強い動物へ進化。ひよこから始めて、最後のゾウを目指す動物マージパズル。",
    controls: "ねらって、はなすと落ちる（タップ / クリック）",
    path: "games/007-yofukashi-suika/index.html",
  },
  {
    id: "006",
    genre: "BOSS RUSH",
    age: "10歳〜",
    color: "#ffe14d",
    title: "コラムブレイカー",
    emoji: "⚡",
    author: "ゲスト",
    date: "2026-08-20",
    description:
      "縦レーザーで挑むボスラッシュ5連戦。ボスと同じ「列」に立てばダメージが入るが、真下は弾幕の的。ボス内部を回るコアを撃ち抜けば3倍ダメージ。",
    controls: "WASD/矢印＋スペース、Shiftで集中 / スマホはドラッグ＋FOCUS",
    path: "games/006-column-breaker/index.html",
  },
  {
    id: "005",
    genre: "PUZZLE SHOT",
    age: "8歳〜",
    color: "#ff4d6d",
    title: "リコシェ・ワン",
    emoji: "🎯",
    author: "スタッフ",
    date: "2026-08-20",
    description:
      "壁に跳ね返る弾で隠れた的を撃ち抜くパズルシューティング。ワープ・重力・動く壁——仕掛けだらけの全10ステージ。",
    controls: "マウスで狙ってクリック / 指でなぞって離す",
    path: "games/005-ricochet-one/index.html",
  },
  {
    id: "004",
    genre: "ARENA SHOOTER",
    age: "10歳〜",
    color: "#ff7a3d",
    title: "アーセナル10",
    emoji: "💥",
    author: "ゲスト",
    date: "2026-08-20",
    description:
      "10種の武器を切り替えて敵の波を迎え撃つアリーナシューティング。ウェーブを重ねて武器を解放し、ボスを撃破せよ。",
    controls: "WASD＋マウス / スマホは左右スティック",
    path: "games/004-arsenal-10/index.html",
  },
  {
    id: "003",
    genre: "SHOOTER",
    age: "7歳〜",
    color: "#3dd6ff",
    title: "マーライオンシューター",
    emoji: "🦁",
    author: "スタッフ",
    date: "2026-08-19",
    description:
      "シンガポールの夜景を守れ。マーライオンの水鉄砲で降り注ぐドリアンを撃ち落とす縦シューティング。流れ星を撃てばボーナス。",
    controls: "←→キー / マウス / スワイプ",
    path: "games/003-merlion-shooter/index.html",
  },
  {
    id: "002",
    genre: "MEMORY",
    age: "6歳〜",
    color: "#b06bff",
    title: "よふかしペアさがし",
    emoji: "👻",
    author: "スタッフ",
    date: "2026-08-19",
    description:
      "裏返ったカードをめくり、同じ絵柄のペアを揃える神経衰弱。全16枚をそろえるまでのタイムアタック。最速記録に挑め。",
    controls: "タップ / クリック",
    path: "games/002-pair-match/index.html",
  },
  {
    id: "001",
    genre: "ACTION",
    age: "6歳〜",
    color: "#ff6fa8",
    title: "はなびらキャッチ",
    emoji: "🌸",
    author: "スタッフ",
    date: "2026-08-19",
    description:
      "夜空から降る花をかごでキャッチする45秒のスコアアタック。星はボーナス、おばけに触れると減点。連続キャッチでハイスコアを狙え。",
    controls: "←→キー / マウス / スワイプ",
    path: "games/001-hanabira-catch/index.html",
  },
];
